### ISSUE TITLE
Running the bin script fails with "env: node\r: No such file or directory"

### ISSUE THREAD

**Issue by royra** [TarVK/ts-cleaner#3]
This is on mac and linux.

Looks like the `./bin/ts-cleaner.js` file was published to npm with DOS CRLF newlines.

Running dos2unix on the file fixes the problem locally.

I think it needs to be republished with unix newlines.

**Comment by TarVK** [comment]
Hey @royra,
Thanks for informing me, I indeed have written and tested it only on windows. Is there any chance you could make a pull request, such that we're sure it works on mac/linux? I can try to correct it myself if you aren't able to, but I won't be able to verify whether it fixes the issue myself.

**Comment by royra** [comment]
The code at GitHub has unix newlines, so I don't see how it's fixable with a PR.

Looks like it's a [known NPM issue](https://github.com/npm/npm/issues/12371). Maybe you should publish a new version with fixed newlines?

**Comment by TarVK** [comment]
Aah alright, my bad. 
I will look into it when I have time.

**Comment by TarVK** [comment]
I tried changing out the CRLF for LF, and published a new version to npm.
I haven't tested anything yet however. I would very much appreciate it if you could verify whether or not this fixed the issue. It also contains your fixes for the async problem.

**Comment by royra** [comment]
Fixed in published version 1.0.4. Thanks!
